# Simple configuration for this.
# Every repository to be updated should be something like this:
# reponame: directory
# crewtinuous-development: /home/pranav/Projects/crewtinuous-development
resume: /var/www/resume
